language: android
jdk: oraclejdk8
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "git clone --depth=1 https://github.com/secure-software-engineering/DroidBench.git /tmp/DroidBench"
install:
 - mvn clean verify -DskipTests=true -B -q
script:
 - mvn clean verify -B -q
 - jdk_switcher use oraclejdk7
 - ./build-maven-jars.py "install -Dgpg.skip"
sudo: false
cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib
